# -*- coding: utf-8 -*-
"""agente_inteligente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1otwzdDN9yLxXU1sbgvZijpAxUDvx2xhe
"""

import random

climas_possiveis = ["sol","chuva","nublado"]

def perceber_clima():
  return random.choices(climas_possiveis)

def decidir_acao(clima):
  if clima == "chuva":
    return "levar guarda-chuva"
  elif clima == "nublado":
    return "levar guarda (melhor prevenir do que remediar)"
  else:
    return "Não precisa levar guarda-chuva"

def agente_simples():
  clima_atual = perceber_clima()
  decisao = decidir_acao(clima_atual)
  print(f"Clima percebido: {clima_atual}")
  print(f"Decisão do agente: {decisao}")

if __name__ == "__main__":
  agente_simples()