# -*- coding: utf-8 -*-
"""analise_criptomoeda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7mnzfINE5ifRrlXdh6BPUCtGdjcmcMl
"""

pip install pycoingecko

pip install plotly

import pandas as pd
import datetime as dt
import time as t
import plotly.graph_objects as go
#from plotly_offline import plot
from pycoingecko import CoinGeckoAPI

cg = CoinGeckoAPI()

cg.ping()

coinList = cg.get_coins_list()
coinDataFrame = pd.DataFrame.from_dict(coinList).sort_values('id').reset_index(drop=True)

print(coinDataFrame)

cg.get_price(ids='bitcoin', vs_currencies='usd')

end_timestamp = int(dt.datetime.now().timestamp())

start_timestamp = int((dt.datetime.now() - dt.timedelta(days=30)).timestamp())

cg.get_coin_market_chart_range_by_id(id='bitcoin', vs_currency='usd', from_timestamp=start_timestamp, to_timestamp=end_timestamp)

cg.get_price(ids='bitcoin,litecoin,ethereum', vs_currencies='usd')

cg.get_coin_market_chart_by_id(id='bitcoin', vs_currency='usd', days=30)

# Inicializando a API CoinGecko
cg = CoinGeckoAPI()

# Definindo o período de tempo para os dados do gráfico (últimos 30 dias)
start_timestamp = int((dt.datetime.now() - dt.timedelta(days=30)).timestamp())
end_timestamp = int(dt.datetime.now().timestamp())

# Obtendo os dados do gráfico de preço para o Bitcoin nos últimos 30 dias
bitcoin_chart_data = cg.get_coin_market_chart_range_by_id(id='bitcoin', vs_currency='usd', from_timestamp=start_timestamp, to_timestamp=end_timestamp)

# Convertendo os dados em um DataFrame Pandas
bitcoin_prices = pd.DataFrame(bitcoin_chart_data['prices'], columns=['timestamp', 'price'])

# Convertendo os timestamps para o formato de data/hora legível
bitcoin_prices['date'] = pd.to_datetime(bitcoin_prices['timestamp'], unit='ms')

# Criando o gráfico de linhas
fig = go.Figure()

fig.add_trace(go.Scatter(x=bitcoin_prices['date'], y=bitcoin_prices['price'], mode='lines', name='Preço (USD)'))

fig.update_layout(title='Preço do Bitcoin nos últimos 30 dias',
                  xaxis_title='Data',
                  yaxis_title='Preço (USD)')

fig.show()