# -*- coding: utf-8 -*-
"""aprendendo_matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BsqeN08yTgjQ4so2fLDx65dFks9zbChQ

O matplotlib é uma biblioteca muito utilizada para gráficos, funciona de forma integrada com o numpy e sua documentação está em https://matplotlib.org/

Inicialmente vamos importar a biblioteca. Como utilizaremos também o numpy vamos importa-lo também.
"""

import numpy as np
import matplotlib.pyplot as plt

"""Criando um gráfico simples. Plotando o resultado de uma função linear."""

x=np.array([0,1,2,3,4,5,6,7,8,9,10,11])
y=0.5*x+5

#cria um gráfico simples
plt.plot(x,y)
#mostra o gráfico
plt.show()

"""Em um mesmo gráfico, podemos plotar diferentes dados, usando diferentes cores, tipos de linha, marcadores."""

x=np.array([0,1,2,3,4,5,6,7,8,9,10,11])
y1=0.5*x+5
y2=-0.3*x+12
y3=np.sin(x)+8 #função seno

#cria um gráfico simples
plt.plot(x,y1, 'r-') #vermelho 'r' linha reta'-'
plt.plot(x,y2, 'b*') #azul'b' com marcador '*' sem linha
plt.plot(x,y3, 'gs--') #verde'g' linha tracejada'--' marcador quadrado's'
#mostra o gráfico
plt.show()

"""Também é possível definir os parâmetros de forma explícita."""

#cria um gráfico simples
plt.plot(x,y1, color='red', linewidth=1) #vermelho 'r' linha reta'-'
plt.plot(x,y2, color='black', marker='*', linestyle='dashed', linewidth=1, markersize=17) #azul'b' com marcador '*' sem linha
plt.plot(x,y3, color=(0, 0.7, 0.8), marker='s', linestyle='none', markersize=12) #verde'g' linha tracejada'--' marcador quadrado's'
#mostra o gráfico
plt.show()

"""Em um gráfico é fundamental colocar de forma correta títulos nos eixos e legendas."""

#cria um gráfico simples
plt.plot(x,y1, color='red', linewidth=1) #vermelho 'r' linha reta'-'
plt.plot(x,y2, color='black', marker='*', linestyle='dashed', linewidth=1, markersize=17) #azul'b' com marcador '*' sem linha
plt.plot(x,y3, color=(0, 0.7, 0.8), marker='s', linestyle='none', markersize=12) #verde'rgb' linha tracejada'--' marcador quadrado's'

#títulos dos eixos
plt.xlabel("x (m)")
plt.xlabel("y (m)")

#legenda
plt.legend(('funcao 1', 'funcao 2', 'funcao 3'))

#salva a figura do gráfico
plt.savefig("grafico.png")

#mostra o gráfico
plt.show()

"""Também é possível salvar a figura em diferentes formatos"""

#cria um gráfico simples
plt.plot(x,y1, color='red', linewidth=1) #vermelho 'r' linha reta'-'
plt.plot(x,y2, color='black', marker='*', linestyle='dashed', linewidth=1, markersize=17) #azul'b' com marcador '*' sem linha
plt.plot(x,y3, color=(0, 0.7, 0.8), marker='s', linestyle='none', markersize=12) #verde'rgb' linha tracejada'--' marcador quadrado's'

#títulos dos eixos
plt.xlabel("x (m)")
plt.xlabel("y (m)")

#legenda
plt.legend(('funcao 1', 'funcao 2', 'funcao 3'))

#salva a figura do gráfico
plt.savefig("grafico.png")

#mostra o gráfico
plt.show()

plt.savefig("grafico.png", dpi=3000) #dpi é resolução, pontos por polegada
plt.savefig("grafico.pdf", format="pdf")
plt.savefig("grafico.svg", format="svg")