# -*- coding: utf-8 -*-
"""calendario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7ymESnlKsC5NSRjt3FR7-lXEu4-exrm
"""

import numpy as np
import matplotlib.pyplot as plt
import calendar
from datetime import datetime

def exibir_calendario(ano, mes):
  cal = calendar.TextCalendar()

  calendario_mensal = cal.formatmonth(ano, mes)

  print(calendario_mensal)

def escolher_data():
  try:
    ano = int(input("Digite o ano (ou deixe vazio para escolher o ano atual)") or datetime.now().year)
    mes = int(input("Digite o mês (ou deixe vazio para escolher o ano atual)") or datetime.now().month)
    exibir_calendario(ano, mes)
  except ValueError:
    print("Por Favor, digite um número válido.")
    escolher_data()

if __name__ == "__main__":
  escolher_data()

def exibir_calendario(ano, mes, meses_a_exibir=12):
    cal = calendar.TextCalendar()
    for i in range(meses_a_exibir):
        # Calcula o mês e o ano, ajustando conforme necessário
        mes_atual = (mes + i - 1) % 12 + 1
        ano_atual = ano + (mes + i - 1) // 12
        print(cal.formatmonth(ano_atual, mes_atual))

if __name__ == "__main__":
    ano_atual = datetime.now().year
    mes_atual = datetime.now().month
    exibir_calendario(ano_atual, mes_atual, 12)  # Ajuste o número de meses a exibir conforme necessário