# -*- coding: utf-8 -*-
"""linha_de_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YwJHDIeu0pJNQQJ_S-Dykimbhtj8voT
"""

import math
import random

LINHAS = 6
COLUNAS = 7
JOGADOR = 1    #nósi
IA = 2         #ia
VAZIO = 0

def criar_tabuleiro():
    return [[VAZIO for _ in range(COLUNAS)] for _ in range(LINHAS)]

def soltar_peca(tabuleiro, linha, coluna, peca):
    tabuleiro[linha][coluna] = peca

def jogada_valida(tabuleiro, coluna):
    return tabuleiro[0][coluna] == VAZIO

def proxima_linha(tabuleiro, coluna):
    for l in range(LINHAS-1, -1, -1):
        if tabuleiro[l][coluna] == VAZIO:
            return l

def imprimir_tabuleiro(tabuleiro):
    for linha in tabuleiro:
        print(" | ".join(str(x) for x in linha))
    print("-" * (COLUNAS * 4 - 1))
    print("   ".join(str(i) for i in range(COLUNAS)))  #mostra índices das colunas


def vitoria(tabuleiro, peca):
    #horizontal
    for l in range(LINHAS):
        for c in range(COLUNAS-3):
            if all(tabuleiro[l][c+i] == peca for i in range(4)):
                return True
    #vertical
    for l in range(LINHAS-3):
        for c in range(COLUNAS):
            if all(tabuleiro[l+i][c] == peca for i in range(4)):
                return True
    #diagonal/
    for l in range(3, LINHAS):
        for c in range(COLUNAS-3):
            if all(tabuleiro[l-i][c+i] == peca for i in range(4)):
                return True
    #diagonal\
    for l in range(LINHAS-3):
        for c in range(COLUNAS-3):
            if all(tabuleiro[l+i][c+i] == peca for i in range(4)):
                return True
    return False

def avaliar_janela(janela, peca):
    pontos = 0
    oponente = JOGADOR if peca == IA else IA

    if janela.count(peca) == 4:
        pontos += 1000
    elif janela.count(peca) == 3 and janela.count(VAZIO) == 1:
        pontos += 100
    elif janela.count(peca) == 2 and janela.count(VAZIO) == 2:
        pontos += 10

    if janela.count(oponente) == 3 and janela.count(VAZIO) == 1:
        pontos -= 80  #Bloquear Logo!

    return pontos

def avaliar_posicao(tabuleiro, peca):
    pontos = 0

    #valorizar centro
    centro_col = [tabuleiro[l][COLUNAS//2] for l in range(LINHAS)]
    pontos += centro_col.count(peca) * 6

    #horizontal
    for l in range(LINHAS):
        for c in range(COLUNAS-3):
            janela = [tabuleiro[l][c+i] for i in range(4)]
            pontos += avaliar_janela(janela, peca)

    #vertical
    for c in range(COLUNAS):
        for l in range(LINHAS-3):
            janela = [tabuleiro[l+i][c] for i in range(4)]
            pontos += avaliar_janela(janela, peca)

    #diagonal /
    for l in range(3, LINHAS):
        for c in range(COLUNAS-3):
            janela = [tabuleiro[l-i][c+i] for i in range(4)]
            pontos += avaliar_janela(janela, peca)

    #diagonal \
    for l in range(LINHAS-3):
        for c in range(COLUNAS-3):
            janela = [tabuleiro[l+i][c+i] for i in range(4)]
            pontos += avaliar_janela(janela, peca)

    return pontos

#o minimax em si

def minimax(tabuleiro, profundidade, alpha, beta, maximizando):
    if profundidade == 0 or vitoria(tabuleiro, JOGADOR) or vitoria(tabuleiro, IA):
        return None, avaliar_posicao(tabuleiro, IA)

    if maximizando:
        valor = -math.inf
        melhor_coluna = random.choice(range(COLUNAS))
        for col in range(COLUNAS):
            if jogada_valida(tabuleiro, col):
                linha = proxima_linha(tabuleiro, col)
                copia = [linha[:] for linha in tabuleiro]
                soltar_peca(copia, linha, col, IA)
                _, novo_valor = minimax(copia, profundidade-1, alpha, beta, False)
                if novo_valor > valor:
                    valor = novo_valor
                    melhor_coluna = col
                alpha = max(alpha, valor)
                if alpha >= beta:
                    break
        return melhor_coluna, valor

    else:  #jogadorminimizando
        valor = math.inf
        melhor_coluna = random.choice(range(COLUNAS))
        for col in range(COLUNAS):
            if jogada_valida(tabuleiro, col):
                linha = proxima_linha(tabuleiro, col)
                copia = [linha[:] for linha in tabuleiro]
                soltar_peca(copia, linha, col, JOGADOR)
                _, novo_valor = minimax(copia, profundidade-1, alpha, beta, True)
                if novo_valor < valor:
                    valor = novo_valor
                    melhor_coluna = col
                beta = min(beta, valor)
                if alpha >= beta:
                    break
        return melhor_coluna, valor

def jogar():
    tabuleiro = criar_tabuleiro()
    fim = False
    turno = random.choice([JOGADOR, IA])  #sorteia quem começa

    PROFUNDIDADE_IA = 0

    while PROFUNDIDADE_IA == 0:
        nivel = input("Escolha o nível de dificuldade (1-Fácil, 2-Médio, 3-Difícil): ")
        if nivel == '1':
            PROFUNDIDADE_IA = 1
        elif nivel == '2':
            PROFUNDIDADE_IA = 3
        elif nivel == '3':
            PROFUNDIDADE_IA = 5
        else:
            print("Opção inválida. Tente novamente.")

    while not fim:
        imprimir_tabuleiro(tabuleiro)

        if turno == JOGADOR:
            col = int(input("Sua jogada (0-6): "))
            if jogada_valida(tabuleiro, col):
                linha = proxima_linha(tabuleiro, col)
                soltar_peca(tabuleiro, linha, col, JOGADOR)

                if vitoria(tabuleiro, JOGADOR):
                    imprimir_tabuleiro(tabuleiro)
                    print("🎉 Você venceu!")
                    fim = True
            else:
                print("Jogada inválida. Tente de novo.")
                continue

        else:  #turno da IA
            print("IA pensando...")
            col, _ = minimax(tabuleiro, PROFUNDIDADE_IA, -math.inf, math.inf, True)
            if jogada_valida(tabuleiro, col):
                linha = proxima_linha(tabuleiro, col)
                soltar_peca(tabuleiro, linha, col, IA)

                if vitoria(tabuleiro, IA):
                    imprimir_tabuleiro(tabuleiro)
                    print("💻 A IA venceu!")
                    fim = True

        # Empate
        if all(not jogada_valida(tabuleiro, c) for c in range(COLUNAS)):
            imprimir_tabuleiro(tabuleiro)
            print("🤝 Empate!")
            fim = True

        turno = IA if turno == JOGADOR else JOGADOR

# Iniciar
jogar()