# -*- coding: utf-8 -*-
"""mapa_a_estrela.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rc1cEtVbK6qBmgm59gDnOdpdz3e0GYg
"""

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import ListedColormap

def mostra_mapa(mapa, caminho):
    ncolunas = mapa["terreno"].shape[1]
    nlinhas = mapa["terreno"].shape[0]

    # Matriz para letras de anotação
    letras = np.array([["" for _ in range(ncolunas)] for _ in range(nlinhas)])

    for passo in caminho:
        letras[passo] = "•"   # bolinha para o caminho
    letras[mapa["entrada"]] = "E"
    letras[mapa["saida"]] = "S"

    # Cria um colormap: 0 = livre, 1 = obstáculo
    cores = ListedColormap(["#d0f0d0", "#444444"])  # verde claro / cinza escuro

    plt.figure(figsize=(6, 6))
    sns.heatmap(
        mapa['terreno'],
        annot=letras,
        fmt="",
        cbar=False,
        cmap=cores,
        linewidths=0.5,
        linecolor='black',
        square=True,
        annot_kws={"size": 12, "weight": "bold", "color": "red"}  # destaque
    )
    plt.title("Mapa com Caminho", fontsize=14, weight="bold")
    plt.show()


# Dimensão do mapa
tam_x = 15
tam_y = 15
terreno = np.zeros((tam_y, tam_x))

entrada = (8, 6)
saida = (0, 14)
mapa = {"terreno": terreno, "entrada": entrada, "saida": saida}

# Obstáculos
obstaculos = [
    (6,5),(7,5),(8,5),(9,5),(10,5),(11,5),(12,5),(13,5),
    (6,7),(7,7),(8,7),(9,7),
    (6,6),
    (9,8),(9,9),(9,10),
    (3,11)
]
for o in obstaculos:
    terreno[o] = 1

# Exemplo de caminho
caminho = [entrada, (7,6), (6,6), (5,6), (4,6), (3,6), (2,6), (1,6), (0,6), (0,7), (0,8), (0,9), (0,10), (0,11), (0,12), (0,13), saida]

mostra_mapa(mapa, caminho)

import copy
def mostra_mapa(mapa, caminho):
    ncolunas = mapa["terreno"].shape[1]
    nlinhas = mapa["terreno"].shape[0]

    # Matriz de anotações (letras/símbolos)
    letras = np.array([["" for _ in range(ncolunas)] for _ in range(nlinhas)])

    # Marca o caminho
    for i, passo in enumerate(caminho):
        if passo not in [mapa["entrada"], mapa["saida"]]:
            letras[passo] = "•"   # bolinha no caminho

    # Entrada e saída
    letras[mapa["entrada"]] = "E"
    letras[mapa["saida"]] = "S"

    # Cores: 0 = livre, 1 = obstáculo, 0.4 = visitado
    cores = ListedColormap(["#d0f0d0", "#444444", "#a0c8ff"])  # livre/obstáculo/visitado

    # Ajusta valores >1
    terreno = np.where(mapa["terreno"] > 1, 1, mapa["terreno"])

    plt.figure(figsize=(6, 6))
    sns.heatmap(
        terreno,
        annot=letras,
        fmt="",
        cbar=False,
        cmap=cores,
        linewidths=0.5,
        linecolor='black',
        square=True,
        annot_kws={"size": 12, "weight": "bold", "color": "red"}
    )
    plt.title("Mapa com Caminho (Busca A*)", fontsize=14, weight="bold")
    plt.show()


# ---- Funções da busca A* ----
def aplica_operacao(estado,op):
    pos=estado["caminho"][-1]
    ops={"N":(-1,0),"S":(1,0),"L":(0,1),"O":(0,-1)}
    passo=(pos[0]+ops[op][0],pos[1]+ops[op][1])
    novo_caminho=copy.deepcopy(estado["caminho"])+[passo]
    novo_estado={"mapa":estado["mapa"],"caminho":novo_caminho}
    return novo_estado

def get_ops_validas(estado):
    ncolunas=estado["mapa"]["terreno"].shape[1]
    nlinhas=estado["mapa"]["terreno"].shape[0]
    pos=estado["caminho"][-1]
    ops={"N":(-1,0),"S":(1,0),"L":(0,1),"O":(0,-1)}
    ops_validas=[]
    for op in ops:
        nova_pos=(pos[0]+ops[op][0],pos[1]+ops[op][1])
        if 0 <= nova_pos[0] < nlinhas and 0 <= nova_pos[1] < ncolunas:
            if estado["mapa"]["terreno"][nova_pos] < 1 and not(nova_pos in estado["caminho"]):
                ops_validas.append(op)
    return ops_validas

def verifica_solucao(estado):
    return estado["caminho"][-1]==estado["mapa"]["saida"]

def calc_c(estado):
    return len(estado["caminho"])

def calc_h(estado):
    s=estado["mapa"]["saida"]
    p=estado["caminho"][-1]
    if len(get_ops_validas(estado))==0:
        return float('inf')
    else:
        return abs(s[0]-p[0])+abs(s[1]-p[1])

def busca_a_estrela(estado_ini,max_niveis):
    quant_estados=0
    folhas=[]
    raiz={"estado":estado_ini,"ops":[],"f":0}
    folhas.append(raiz)
    niveis=0
    while(niveis<max_niveis):
        niveis=niveis+1
        melhor_folha=folhas[0]
        #----escolhe a melhor folha
        for folha in folhas:
            if folha["f"]<melhor_folha["f"]:
                melhor_folha=folha
        #---------------------------
        folhas.remove(melhor_folha)
        operacoes=get_ops_validas(melhor_folha["estado"])
        for op in operacoes:
            estado=aplica_operacao(melhor_folha["estado"],op)
            estado["mapa"]["terreno"][estado["caminho"][-1]]=0.4  # marca como visitado
            quant_estados+=1
            nova_folha={"estado":estado,"ops":melhor_folha["ops"]+[op],"f":0}
            f=calc_c(nova_folha["estado"])+calc_h(nova_folha["estado"])
            nova_folha["f"]=f
            folhas.append(nova_folha)
            if verifica_solucao(nova_folha["estado"]):
                return nova_folha["estado"], nova_folha["ops"],quant_estados
    return None


# ---- Criando o mapa ----
tam_x=15
tam_y=15
terreno=np.zeros((tam_y,tam_x))
entrada=(8,6)
saida=(0,14)
mapa={"terreno":terreno,"entrada":entrada,"saida":saida}

# Obstáculos
obstaculos = [
    (6,5),(7,5),(8,5),(9,5),(10,5),(11,5),(12,5),(13,5),
    (6,7),(7,7),(8,7),(9,7),
    (6,6),
    (9,8),(9,9),(9,10),
    (3,11)
]
for o in obstaculos:
    terreno[o]=1

# Corrige valores
for i in range(mapa["terreno"].shape[0]):
    for j in range(mapa["terreno"].shape[1]):
        if mapa["terreno"][i,j]<1:
            mapa["terreno"][i,j]=0

# ---- Executa a busca A* ----
estado_ini={"mapa":mapa,"caminho":[mapa["entrada"]]}
mostra_mapa(estado_ini["mapa"],estado_ini["caminho"])
max_niveis=100000
estado,ops,quant_estados=busca_a_estrela(estado_ini,max_niveis)
mostra_mapa(estado["mapa"],estado["caminho"])
print("ops:",ops)
print("quant estados:",quant_estados)