# -*- coding: utf-8 -*-
"""polinomio_interpolador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1myjl45jEkyEJsaz8UUmKxa5e-oi4hah2
"""

import numpy as np
import matplotlib.pyplot as plt

# Pontos fornecidos (tempo em minutos e temperatura)
tempos = np.array([0, 120, 240, 360, 480])
temperaturas = np.array([25, 260, 395, 460, 515])

def polinomio_interpolador_lagrange(x, tempos, temperaturas):
    n = len(tempos)
    resultado = 0.0

    for i in range(n):
        termo = temperaturas[i]
        for j in range(n):
            if j != i:
                termo *= (x - tempos[j]) / (tempos[i] - tempos[j])
        resultado += termo

    return resultado

# Ponto para o qual queremos interpolar a temperatura (por exemplo, 150 minutos)
ponto = 150

# Calculando a temperatura interpolada para o ponto dado
temperatura_interpolada = polinomio_interpolador_lagrange(ponto, tempos, temperaturas)
print("Temperatura interpolada em", ponto, "minutos:", temperatura_interpolada)

# Gerar pontos para o gráfico
x_vals = np.linspace(0, 480, 100)  # Valores de tempo de 0 a 480 minutos
y_vals = [polinomio_interpolador_lagrange(x, tempos, temperaturas) for x in x_vals]

# Plotar os pontos dados
plt.scatter(tempos, temperaturas, color='red', label='Pontos dados')

# Plotar o polinômio interpolador
plt.plot(x_vals, y_vals, label='Polinômio interpolador')

# Configurações adicionais do gráfico
plt.title('Interpolação de Temperatura')
plt.xlabel('Tempo (minutos)')
plt.ylabel('Temperatura')
plt.legend()
plt.grid(True)

# Mostrar o gráfico
plt.show()