# -*- coding: utf-8 -*-
"""pythonTestesBasicos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6_ptARjgUNw8XhVUMeUTJ21gQNMGY_K
"""

# Criando uma lista
lista = [1, 2, 3, 4, 5]

# Acessando elementos da lista
print(lista[0])  # Saída: 1
print(lista[2])  # Saída: 3
print(lista[1], lista[2]) # Saída: 2 3

# Adicionando elementos à lista
lista.append(6)

print(lista) # Saída: [1, 2, 3, 4, 5, 6]

# Removendo elementos da lista
lista.remove(3)

print(lista)  # Saída: [1, 2, 4, 5, 6]

"""Tuplas:

As tuplas são coleções ordenadas e imutáveis de itens.
"""

# Criando uma tupla
tupla = (1, 2, 3, 4, 5)

# Acessando elementos da tupla
print(tupla[0])  # Saída: 1
print(tupla[2])  # Saída: 3

"""Dicionários:

Os dicionários são coleções não ordenadas de pares chave-valor.
"""

# Criando um dicionário
dicionario = {"a": 1, "b": 2, "c": 3}

# Acessando valores através das chaves
print(dicionario["a"])  # Saída: 1
print(dicionario["c"])  # Saída: 3

# Adicionando um novo par chave-valor
dicionario["d"] = 4
print(dicionario)  # Saída: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

# Removendo um par chave-valor
del dicionario["b"]
print(dicionario)  # Saída: {'a': 1, 'c': 3, 'd': 4}

"""Conjuntos:

Os conjuntos são coleções desordenadas de elementos únicos.

"""

# Criando um conjunto
conjunto = {1, 2, 3, 4, 5}

# Adicionando elementos ao conjunto
conjunto.add(6)
print(conjunto)  # Saída: {1, 2, 3, 4, 5, 6}

# Removendo elementos do conjunto
conjunto.remove(3)
print(conjunto)  # Saída: {1, 2, 4, 5, 6}

# Função que ordena utilizando o método bubble sort
def bubble_sort(arr):
  n = len(arr)
  for i in range(n):
    for j in range(0, n-i-1):
      if arr[j] > arr[j+1]:
        arr[j], arr[j+1] = arr[j+1], arr[j]

lista = [2003, 2005, 2014, 2013, 2015, 2013, 1999, 2016, 2019, 2018, 2003, 2007, 2009, 2009, 2012, 2004, 2004, 2005, 2000, 2017, 2020, 2007, 2010, 2004, 2012, 2013, 2007, 2017, 2011, 1996, 2003, 2005, 2016, 2003, 2004, 2010, 2006, 2015, 2005, 2017, 2011, 2019, 2018, 2004, 2009, 2018, 2019, 2006, 2008, 2012]
bubble_sort(lista)
print(lista)

#Função que ordena usando o método selection sort
def selection_sort(arr):
    n = len(arr)
    # Percorre todos os elementos da lista
    for i in range(n):
        # Assume que o menor elemento é o primeiro elemento da sublista ainda não ordenada
        min_index = i
        # Percorre a sublista ainda não ordenada para encontrar o menor elemento
        for j in range(i+1, n):
            # Se o elemento atual for menor que o menor elemento encontrado até agora
            if arr[min_index] > arr[j]:
                # Atualiza o índice do menor elemento
                min_index = j
        # Troca o menor elemento encontrado com o primeiro elemento da sublista ainda não ordenada
        arr[i], arr[min_index] = arr[min_index], arr[i]

# Exemplo de uso
lista = [64, 34, 25, 12, 22, 11, 90]
selection_sort(lista)
print("Lista ordenada:", lista)

# Função que ordena utilizando o método insertion sort
def insertion_sort(arr):
    n = len(arr)

    # Percorre todos os elementos da lista, exceto o primeiro
    for i in range(1, n):

        # Assume que o elemento atual pertence à sublista ordenada
        key = arr[i]
        j = i-1

        # Move elementos da sublista ordenada à direita do elemento atual, se necessário
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1

        # Insere o elemento atual na posição correta na sublista ordenada
        arr[j + 1] = key

# Exemplo de uso
lista = [64, 34, 25, 12, 22, 11, 90]
insertion_sort(lista)
print("Lista ordenada:", lista)